# Generated by Django 2.2.9 on 2020-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('establecimiento_code', models.CharField(max_length=3, null=True)),
                ('punto_venta_code', models.CharField(max_length=3)),
            ],
        ),
    ]
