# Generated by Django 2.2.9 on 2020-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anubisoft_billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbilling',
            name='secuencial',
            field=models.IntegerField(default=1),
        ),
    ]
